version: '3.6'
services:
  postgres:
    volumes:
      - db_data:/var/lib/postgresql/data
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5430:5432'
volumes:
  db_data:
